twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null

#    Eu inseri esse link para usar o template do bootstrap no synfony
    form_theme:
        - bootstrap_4_layout.html.twig